# Reccomendation systems and matrix factorization

In [11]:
import numpy as np


In [12]:

def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    '''
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: |D| * K (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''
    Q = Q.T

    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with a and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = np.dot(P,Q)

        e = 0

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:

            break

    return P, Q.T

In [14]:
R = [

     [5,3,0,1],

     [4,0,0,1],

     [1,1,0,5],

     [1,0,0,4],

     [0,1,5,4],
    
     [2,1,3,0],

    ]

R = np.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 5

 
P = np.random.rand(N,K)
Q = np.random.rand(M,K)

 

nP, nQ = matrix_factorization(R, P, Q, K)

print(nP,'\n',nQ)

nR = np.dot(nP, nQ.T)

[[ 1.20240606 -0.11174763  1.40282051  0.72548966  1.23378797]
 [ 0.48381414  0.38847114  1.50285771  0.48944556  0.42536389]
 [ 0.65926498  1.92865056 -0.18551425  0.42383444  0.38205828]
 [ 0.90011508  1.22614539 -0.36390508  0.09142982  0.91922067]
 [ 0.5134415   1.53598515  1.01510828 -0.18564866  1.06781069]
 [ 0.6179671   0.88203217  0.52803688  0.15957149  0.32611145]] 
 [[ 0.53991441  0.21915302  1.96378829  0.52821591  0.98959219]
 [ 1.03170638 -0.11010547  0.34291717  0.89753562  0.46477219]
 [ 1.09872809  1.58326772  1.18851528  0.31408468  0.7724855 ]
 [ 0.60330625  2.15725149 -0.34641157  0.18340436  0.70764989]]


In [ ]:
print(R)
print(nR)

[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]
 [2 1 3 0]]
[[4.98432597 2.96434211 4.695791   1.00221484]
 [3.97046504 2.27454819 3.9242913  0.9999445 ]
 [1.02728262 0.93412167 3.90578234 4.96992816]
 [0.98843743 0.71498359 3.66086552 3.97985621]
 [2.11521101 1.10008529 4.94645641 4.00172386]
 [1.99633714 0.94407259 3.02082163 1.46386882]]
